const CURRENCY = 'CAD';
const PRECISION = 2;
const RESPONSE_CODE_400 = 400;
const RESPONSE_CODE_200 = 200;

module.exports = {
  CURRENCY: CURRENCY,
  PRECISION: PRECISION,
  RESPONSE_CODE_400: RESPONSE_CODE_400,
  RESPONSE_CODE_200: RESPONSE_CODE_200,
};
